# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"printhello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://jsalminen.github.io/serverlogsanalytics/"

git_url = "https://github.com/jsalminen/serverlogsanalytics/tree/master/"

def custom_doc_links(name): return None
