# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['sayhello']

# Cell
def sayhello(name = "Stranger"):
    "Print a greeting for a name defined as a parameter"
    return("Hello " + str(name))