# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['printhello']

# Cell
def printhello(name = "stranges"):
    "Print a greeting for a name defined as a parameter"
    print("Hello " + str(name))